---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: "11.10.4"
provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      box: bandersnatch/ubuntu-1204
      run_list:
        -recipe[yum]
          -recipe[apt]

#  - name: centos-6.4

suites:
  - name: default
    run_list: ["recipe[webmin::default]"]
    attributes: {}
